// 1. File naming — api.users.$userId.ts
// React Router uses the file name as a URL hint (dots become /, $ becomes a
// dynamic segment). The name here is just for your own organisation though —
// the actual URL is defined in routes.ts.

// 2. Registered in routes.ts
// route('api/users/:userId', 'routes/api.users.$userId.ts')
// :userId is the dynamic segment. React Router makes it available as
// params.userId inside the loader.

// 3. The loader export
// A loader is called on every GET request to the route. Returning
// Response.json(...) makes it behave like a pure JSON API endpoint —
// no HTML, no component needed. The route file has no default export,
// so React Router never tries to render a page for it.

// 4. Type safety
// Route.LoaderArgs is auto-generated by React Router into .react-router/types/
// from the route registration, giving you a typed params.userId.

import type { Route } from './+types/api.users.$userId';

// Fake user data — replace with a real DB/service call
const USERS: Record<number, { id: number; name: string; email: string }> = {
	0: { id: 0, name: 'Alice', email: 'alice@example.com' },
	1: { id: 1, name: 'Bob', email: 'bob@example.com' },
	2: { id: 2, name: 'Carol', email: 'carol@example.com' },
};

export async function loader({ params }: Route.LoaderArgs) {
	const userId = Number(params.userId);

	if (isNaN(userId)) {
		return Response.json({ error: 'Invalid user ID' }, { status: 400 });
	}

	const user = USERS[userId];

	if (!user) {
		return Response.json({ error: 'User not found' }, { status: 404 });
	}

	return Response.json(user);
}
